include config.mk

# C source code files
C_FILES := src/devtab.c \
           src/format.c \
           src/kprintf.c \
           src/testblks.c \
           src/ufs1to2.c \
           src/ufs\#cd.c \
           src/ufs\#cerr.c \
           src/ufs\#crte.c \
           src/ufscwdfr.c \
           src/ufscwdnw.c \
           src/ufsdaadr.c \
           src/ufsdaalc.c \
           src/ufsdaalf.c \
           src/ufsdachg.c \
           src/ufsdacon.c \
           src/ufsdadal.c \
           src/ufsdadmp.c \
           src/ufsdaexp.c \
           src/ufsdafor.c \
           src/ufsdafup.c \
           src/ufsdalnk.c \
           src/ufsdalp1.c \
           src/ufsdalp2.c \
           src/ufsdalst.c \
           src/ufsdarml.c \
           src/ufsdarms.c \
           src/ufsdasan.c \
           src/ufsdaulk.c \
           src/ufs\#dcls.c \
           src/ufsdirad.c \
           src/ufsdircv.c \
           src/ufsdirfn.c \
           src/ufsdirrm.c \
           src/ufsdirrp.c \
           src/ufsdkcls.c \
           src/ufsdkcsb.c \
           src/ufsdkfbf.c \
           src/ufsdkgbf.c \
           src/ufsdkopn.c \
           src/ufsdkrd.c \
           src/ufsdkrdn.c \
           src/ufsdkrsb.c \
           src/ufsdkwbt.c \
           src/ufsdkwsb.c \
           src/ufsdkwt.c \
           src/ufsdkwtn.c \
           src/ufsdmpin.c \
           src/ufs\#dopn.c \
           src/ufs\#drd.c \
           src/ufsdstv.c \
           src/ufsdvcls.c \
           src/ufsdvctl.c \
           src/ufsdverr.c \
           src/ufsdvfnd.c \
           src/ufsdvfre.c \
           src/ufsdvgtc.c \
           src/ufsdvini.c \
           src/ufsdvnew.c \
           src/ufsdvnul.c \
           src/ufsdvopn.c \
           src/ufsdvptc.c \
           src/ufsdvrd.c \
           src/ufsdvsee.c \
           src/ufsdvtrm.c \
           src/ufsdvwt.c \
           src/ufs\#fcls.c \
           src/ufs\#feof.c \
           src/ufs\#ferr.c \
           src/ufsfgetc.c \
           src/ufsfgetn.c \
           src/ufs\#fgtc.c \
           src/ufs\#fgts.c \
           src/ufsfialc.c \
           src/ufsfidal.c \
           src/ufsfifre.c \
           src/ufsfilbn.c \
           src/ufsfilbz.c \
           src/ufsfilnk.c \
           src/ufsfimod.c \
           src/ufsfinew.c \
           src/ufsfiren.c \
           src/ufsfisym.c \
           src/ufs\#fopn.c \
           src/ufs\#fptc.c \
           src/ufs\#fpts.c \
           src/ufsfputc.c \
           src/ufsfputn.c \
           src/ufs\#frd.c \
           src/ufsfree.c \
           src/ufs\#fsee.c \
           src/ufsfstab.c \
           src/ufs\#fsyn.c \
           src/ufsfsync.c \
           src/ufs\#fwt.c \
           src/ufs\#gace.c \
           src/ufs\#gcre.c \
           src/ufs\#gcwd.c \
           src/ufs\#gsys.c \
           src/ufsinacc.c \
           src/ufsinaex.c \
           src/ufsinalc.c \
           src/ufsinard.c \
           src/ufsinawt.c \
           src/ufsindal.c \
           src/ufsindmp.c \
           src/ufsinfor.c \
           src/ufsinfup.c \
           src/ufsinget.c \
           src/ufsinidl.c \
           src/ufsinit.c \
           src/ufsinlod.c \
           src/ufsinmvd.c \
           src/ufsinrel.c \
           src/ufsinsan.c \
           src/ufsinsdi.c \
           src/ufsinsmi.c \
           src/ufsinuse.c \
           src/ufsinwbk.c \
           src/ufsiofre.c \
           src/ufsionew.c \
           src/ufs\#lkup.c \
           src/ufs\#md.c \
           src/ufs\#lmin.c \
           src/ufsmount.c \
           src/ufsnew.c \
           src/ufsnmfnd.c \
           src/ufsnmini.c \
           src/ufsnmmnt.c \
           src/ufsnmsrt.c \
           src/ufs\#open.c \
           src/ufspanic.c \
           src/ufspgfls.c \
           src/ufspgfre.c \
           src/ufspglck.c \
           src/ufspgnew.c \
           src/ufspgrfb.c \
           src/ufspgrfl.c \
           src/ufspgrfr.c \
           src/ufspgrin.c \
           src/ufspgrlk.c \
           src/ufspgrlp.c \
           src/ufspgrnd.c \
           src/ufspgrrd.c \
           src/ufspgrrn.c \
           src/ufspgrul.c \
           src/ufspgrwn.c \
           src/ufspgrwt.c \
           src/ufspgunl.c \
           src/ufs\#rd.c \
           src/ufs\#rem.c \
           src/ufs\#sace.c \
           src/ufs\#scre.c \
           src/ufs\#scwd.c \
           src/ufs\#soff.c \
           src/ufs\#son.c \
           src/ufs\#ssys.c \
           src/ufssyget.c \
           src/ufs\#sync.c \
           src/ufssynew.c \
           src/ufssytrm.c \
           src/ufstest.c \
           src/ufsunmal.c \
           src/ufsunmdd.c \
           src/ufsunmin.c \
           src/ufsunmpa.c \
           src/ufsunmvd.c \
           src/ufsvdfre.c \
           src/ufsvdnew.c \
           src/ufsvdrd.c \
           src/ufsvdrdn.c \
           src/ufsvdwt.c \
           src/ufsvdwtn.c \
           src/xclose.c \
           src/xcontrol.c \
           src/xgetc.c \
           src/xioerr.c \
           src/xionull.c \
           src/xputc.c \
           src/xread.c \
           src/xwrite.c

# Assembler source files
A_FILES :=

include rules.mk
